CREATE SCHEMA `baixe`;
CREATE TABLE `baixe`.`new_table` (
  `MaXe` INT NOT NULL,
  `Image1` VARCHAR(45) NULL DEFAULT NULL,
  `Image2` VARCHAR(45) NULL DEFAULT NULL,
  `Time` TIME NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Note` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MaXe`));